version: 2
updates:
- package-ecosystem: pip
  directory: "/bodhi-client/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: all
- package-ecosystem: pip
  directory: "/bodhi-messages/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: all
- package-ecosystem: pip
  directory: "/bodhi-server/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  allow:
  - dependency-type: all
