---
- name: change config to use the koji buildsystem
  ini_file:
    path: /home/vagrant/development.ini
    section: app:main
    option: buildsystem
    value: koji

- name: change config to use the stg kojihub
  ini_file:
    path: /home/vagrant/development.ini
    section: app:main
    option: koji_hub
    value: https://koji.stg.fedoraproject.org/kojihub

- name: change config to use the stg koji
  ini_file:
    path: /home/vagrant/development.ini
    section: app:main
    option: koji_web_url
    value: https://koji.stg.fedoraproject.org/koji/

- name: change config to use the stg kerberos
  ini_file:
    path: /home/vagrant/development.ini
    section: app:main
    option: krb_principal
    value: "{{ staging_fas }}@STG.FEDORAPROJECT.ORG"

- name: change config to use the pagure for acls
  ini_file:
    path: /home/vagrant/development.ini
    section: app:main
    option: acl_system
    value: pagure

- name: change config to use stg pagure for acls
  ini_file:
    path: /home/vagrant/development.ini
    section: app:main
    option: pagure_url
    value: https://src.stg.fedoraproject.org/
