amqp_url = "amqp://rabbitmq/"
callback = "bodhi.server.consumers:Consumer"
topic_prefix = "org.fedoraproject.prod"

[[bindings]]
queue = "bodhi"
exchange = "amq.topic"
routing_keys = [
    "org.fedoraproject.*.buildsys.tag",
    "org.fedoraproject.*.greenwave.decision.update",
]

[client_properties]
app = "bodhi"

[queues.bodhi]
durable = true
auto_delete = false
exclusive = false
arguments = {}

[log_config]
version = 1
disable_existing_loggers = true

[log_config.formatters.simple]
format = "[%(name)s %(levelname)s] %(message)s"

[log_config.handlers.console]
class = "logging.StreamHandler"
formatter = "simple"
stream = "ext://sys.stdout"

[log_config.loggers.fedora_messaging]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.root]
level = "WARNING"
handlers = ["console"]
