---
- name: Install dev packages
  dnf:
      name: "{{ item }}"
      state: present
  with_items:
      - createrepo_c
      - freetype-devel
      - gcc
      - git
      - graphviz
      - koji
      - liberation-mono-fonts
      - libffi-devel
      - libjpeg-devel
      - libjpeg-turbo-devel
      - openssl-devel
      - packagedb-cli
      - pcaro-hermit-fonts
      - postgresql-devel
      - python
      - python-alembic
      - python-arrow
      - python-bugzilla
      - python-bunch
      - python-click
      - python-cornice
      - python-cornice-sphinx
      - python-devel
      - python-dogpile-cache
      - python-fedora
      - python-kitchen
      - python-librepo
      - python-mock
      - python-nose
      - python-openid
      - python-pillow
      - python-progressbar
      - python-psycopg2
      - python-pydns
      - python-pylibravatar
      - python-pyramid
      - python-pyramid-mako
      - python-pyramid-fas-openid
      - python-pyramid-tm
      - python-simplemediawiki
      - python-sqlalchemy
      - python-webhelpers
      - python-webob
      - python-webtest
      - python-zmq
      - python-zope-sqlalchemy
      - python2-colander
      - python2-createrepo_c
      - python2-cryptography
      - python2-fedmsg-atomic-composer
      - python2-fedmsg-consumers
      - python2-flake8
      - python2-nose-cov
      - python2-markdown
      - python2-sphinx
      # We can switch this to python2-sqlalchemy_schemadisplay once
      # https://bodhi.fedoraproject.org/updates/FEDORA-2017-e54acedb77 is stable
      - https://kojipkgs.fedoraproject.org//packages/python-sqlalchemy_schemadisplay/1.3/1.fc24/noarch/python2-sqlalchemy_schemadisplay-1.3-1.fc24.noarch.rpm
      - python2-waitress
      - redhat-rpm-config
      - zlib-devel

# This isn't packaged in Fedora yet, but it's only a development tool (we should still add it)
- name: pip install debugtoolbar
  pip:
      name: pyramid_debugtoolbar

# This isn't packaged in Fedora yet, but there is a package review open https://bugzilla.redhat.com/show_bug.cgi?id=1409654
- name: pip install pydocstyle
  pip:
      name: pydocstyle

- name: Install bodhi in developer mode
  command: python /home/vagrant/bodhi/setup.py develop
  args:
      chdir: /home/vagrant/bodhi
      creates: /usr/lib/python2.7/site-packages/bodhi.egg-link

- name: Retrieve database dump
  get_url:
      url: https://infrastructure.fedoraproject.org/infra/db-dumps/bodhi2.dump.xz
      dest: /tmp/bodhi2.dump.xz

- shell: xzcat /tmp/bodhi2.dump.xz | runuser -l postgres -c 'psql bodhi2' && touch /home/vagrant/.db-imported
  args:
      creates: /home/vagrant/.db-imported

- command: cp /home/vagrant/bodhi/development.ini.example /home/vagrant/bodhi/development.ini
  args:
      creates: /home/vagrant/bodhi/development.ini

- name: Switch the database connection to postgres
  replace:
    dest: /home/vagrant/bodhi/development.ini
    regexp: "^sqlalchemy.url = sqlite.*$"
    replace: "sqlalchemy.url = postgresql://postgres:anypasswordworkslocally@localhost/bodhi2"

- name: Apply database migrations
  command: alembic upgrade head
  args:
      chdir: /home/vagrant/bodhi

- name: Install the systemd unit
  copy:
      src: bodhi.service
      dest: /etc/systemd/system/bodhi.service
      mode: 0644

- name: Install the .bashrc
  copy:
      src: .bashrc
      dest: /home/vagrant/.bashrc
      mode: 0644
      owner: vagrant
      group: vagrant

- name: Install the motd
  copy:
      src: motd
      dest: /etc/motd
      mode: 0644

- name: Start and enable the bodhi service
  service:
      name: bodhi
      state: started
      enabled: yes
