on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
      - '7.0'
      - '7.1'
    paths:
      - docs/**

name: Build Docs and push results to gh-pages branch

permissions:
  contents: write

jobs:
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: pip install click sphinx sqlalchemy_schemadisplay

      - name: Build the docs
        run: devel/ci/bodhi-ci docs -r pip

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: test_results/pip-docs/html
          target-folder: ${{ github.ref_name }}
    strategy:
      fail-fast: false
